namespace Fulma

module FontAwesome5 =

    module Fa =

        [<StringEnum>]
        type Solid =
            | [<CompiledName("fas fa-ad")>] Ad
            | [<CompiledName("fas fa-address-book")>] AddressBook
            | [<CompiledName("fas fa-address-card")>] AddressCard
            | [<CompiledName("fas fa-adjust")>] Adjust
            | [<CompiledName("fas fa-air-freshener")>] AirFreshener
            | [<CompiledName("fas fa-align-center")>] AlignCenter
            | [<CompiledName("fas fa-align-justify")>] AlignJustify
            | [<CompiledName("fas fa-align-left")>] AlignLeft
            | [<CompiledName("fas fa-align-right")>] AlignRight
            | [<CompiledName("fas fa-allergies")>] Allergies
            | [<CompiledName("fas fa-ambulance")>] Ambulance
            | [<CompiledName("fas fa-american-sign-language-interpreting")>] AmericanSignLanguageInterpreting
            | [<CompiledName("fas fa-anchor")>] Anchor
            | [<CompiledName("fas fa-angle-double-down")>] AngleDoubleDown
            | [<CompiledName("fas fa-angle-double-left")>] AngleDoubleLeft
            | [<CompiledName("fas fa-angle-double-right")>] AngleDoubleRight
            | [<CompiledName("fas fa-angle-double-up")>] AngleDoubleUp
            | [<CompiledName("fas fa-angle-down")>] AngleDown
            | [<CompiledName("fas fa-angle-left")>] AngleLeft
            | [<CompiledName("fas fa-angle-right")>] AngleRight
            | [<CompiledName("fas fa-angle-up")>] AngleUp
            | [<CompiledName("fas fa-angry")>] Angry
            | [<CompiledName("fas fa-ankh")>] Ankh
            | [<CompiledName("fas fa-apple-alt")>] AppleAlt
            | [<CompiledName("fas fa-archive")>] Archive
            | [<CompiledName("fas fa-archway")>] Archway
            | [<CompiledName("fas fa-arrow-alt-circle-down")>] ArrowAltCircleDown
            | [<CompiledName("fas fa-arrow-alt-circle-left")>] ArrowAltCircleLeft
            | [<CompiledName("fas fa-arrow-alt-circle-right")>] ArrowAltCircleRight
            | [<CompiledName("fas fa-arrow-alt-circle-up")>] ArrowAltCircleUp
            | [<CompiledName("fas fa-arrow-circle-down")>] ArrowCircleDown
            | [<CompiledName("fas fa-arrow-circle-left")>] ArrowCircleLeft
            | [<CompiledName("fas fa-arrow-circle-right")>] ArrowCircleRight
            | [<CompiledName("fas fa-arrow-circle-up")>] ArrowCircleUp
            | [<CompiledName("fas fa-arrow-down")>] ArrowDown
            | [<CompiledName("fas fa-arrow-left")>] ArrowLeft
            | [<CompiledName("fas fa-arrow-right")>] ArrowRight
            | [<CompiledName("fas fa-arrow-up")>] ArrowUp
            | [<CompiledName("fas fa-arrows-alt")>] ArrowsAlt
            | [<CompiledName("fas fa-arrows-alt-h")>] ArrowsAltH
            | [<CompiledName("fas fa-arrows-alt-v")>] ArrowsAltV
            | [<CompiledName("fas fa-assistive-listening-systems")>] AssistiveListeningSystems
            | [<CompiledName("fas fa-asterisk")>] Asterisk
            | [<CompiledName("fas fa-at")>] At
            | [<CompiledName("fas fa-atlas")>] Atlas
            | [<CompiledName("fas fa-atom")>] Atom
            | [<CompiledName("fas fa-audio-description")>] AudioDescription
            | [<CompiledName("fas fa-award")>] Award
            | [<CompiledName("fas fa-backspace")>] Backspace
            | [<CompiledName("fas fa-backward")>] Backward
            | [<CompiledName("fas fa-balance-scale")>] BalanceScale
            | [<CompiledName("fas fa-ban")>] Ban
            | [<CompiledName("fas fa-band-aid")>] BandAid
            | [<CompiledName("fas fa-barcode")>] Barcode
            | [<CompiledName("fas fa-bars")>] Bars
            | [<CompiledName("fas fa-baseball-ball")>] BaseballBall
            | [<CompiledName("fas fa-basketball-ball")>] BasketballBall
            | [<CompiledName("fas fa-bath")>] Bath
            | [<CompiledName("fas fa-battery-empty")>] BatteryEmpty
            | [<CompiledName("fas fa-battery-full")>] BatteryFull
            | [<CompiledName("fas fa-battery-half")>] BatteryHalf
            | [<CompiledName("fas fa-battery-quarter")>] BatteryQuarter
            | [<CompiledName("fas fa-battery-three-quarters")>] BatteryThreeQuarters
            | [<CompiledName("fas fa-bed")>] Bed
            | [<CompiledName("fas fa-beer")>] Beer
            | [<CompiledName("fas fa-bell")>] Bell
            | [<CompiledName("fas fa-bell-slash")>] BellSlash
            | [<CompiledName("fas fa-bezier-curve")>] BezierCurve
            | [<CompiledName("fas fa-bible")>] Bible
            | [<CompiledName("fas fa-bicycle")>] Bicycle
            | [<CompiledName("fas fa-binoculars")>] Binoculars
            | [<CompiledName("fas fa-birthday-cake")>] BirthdayCake
            | [<CompiledName("fas fa-blender")>] Blender
            | [<CompiledName("fas fa-blender-phone")>] BlenderPhone
            | [<CompiledName("fas fa-blind")>] Blind
            | [<CompiledName("fas fa-bold")>] Bold
            | [<CompiledName("fas fa-bolt")>] Bolt
            | [<CompiledName("fas fa-bomb")>] Bomb
            | [<CompiledName("fas fa-bone")>] Bone
            | [<CompiledName("fas fa-bong")>] Bong
            | [<CompiledName("fas fa-book")>] Book
            | [<CompiledName("fas fa-book-dead")>] BookDead
            | [<CompiledName("fas fa-book-open")>] BookOpen
            | [<CompiledName("fas fa-book-reader")>] BookReader
            | [<CompiledName("fas fa-bookmark")>] Bookmark
            | [<CompiledName("fas fa-bowling-ball")>] BowlingBall
            | [<CompiledName("fas fa-box")>] Box
            | [<CompiledName("fas fa-box-open")>] BoxOpen
            | [<CompiledName("fas fa-boxes")>] Boxes
            | [<CompiledName("fas fa-braille")>] Braille
            | [<CompiledName("fas fa-brain")>] Brain
            | [<CompiledName("fas fa-briefcase")>] Briefcase
            | [<CompiledName("fas fa-briefcase-medical")>] BriefcaseMedical
            | [<CompiledName("fas fa-broadcast-tower")>] BroadcastTower
            | [<CompiledName("fas fa-broom")>] Broom
            | [<CompiledName("fas fa-brush")>] Brush
            | [<CompiledName("fas fa-bug")>] Bug
            | [<CompiledName("fas fa-building")>] Building
            | [<CompiledName("fas fa-bullhorn")>] Bullhorn
            | [<CompiledName("fas fa-bullseye")>] Bullseye
            | [<CompiledName("fas fa-burn")>] Burn
            | [<CompiledName("fas fa-bus")>] Bus
            | [<CompiledName("fas fa-bus-alt")>] BusAlt
            | [<CompiledName("fas fa-business-time")>] BusinessTime
            | [<CompiledName("fas fa-calculator")>] Calculator
            | [<CompiledName("fas fa-calendar")>] Calendar
            | [<CompiledName("fas fa-calendar-alt")>] CalendarAlt
            | [<CompiledName("fas fa-calendar-check")>] CalendarCheck
            | [<CompiledName("fas fa-calendar-minus")>] CalendarMinus
            | [<CompiledName("fas fa-calendar-plus")>] CalendarPlus
            | [<CompiledName("fas fa-calendar-times")>] CalendarTimes
            | [<CompiledName("fas fa-camera")>] Camera
            | [<CompiledName("fas fa-camera-retro")>] CameraRetro
            | [<CompiledName("fas fa-campground")>] Campground
            | [<CompiledName("fas fa-cannabis")>] Cannabis
            | [<CompiledName("fas fa-capsules")>] Capsules
            | [<CompiledName("fas fa-car")>] Car
            | [<CompiledName("fas fa-car-alt")>] CarAlt
            | [<CompiledName("fas fa-car-battery")>] CarBattery
            | [<CompiledName("fas fa-car-crash")>] CarCrash
            | [<CompiledName("fas fa-car-side")>] CarSide
            | [<CompiledName("fas fa-caret-down")>] CaretDown
            | [<CompiledName("fas fa-caret-left")>] CaretLeft
            | [<CompiledName("fas fa-caret-right")>] CaretRight
            | [<CompiledName("fas fa-caret-square-down")>] CaretSquareDown
            | [<CompiledName("fas fa-caret-square-left")>] CaretSquareLeft
            | [<CompiledName("fas fa-caret-square-right")>] CaretSquareRight
            | [<CompiledName("fas fa-caret-square-up")>] CaretSquareUp
            | [<CompiledName("fas fa-caret-up")>] CaretUp
            | [<CompiledName("fas fa-cart-arrow-down")>] CartArrowDown
            | [<CompiledName("fas fa-cart-plus")>] CartPlus
            | [<CompiledName("fas fa-cat")>] Cat
            | [<CompiledName("fas fa-certificate")>] Certificate
            | [<CompiledName("fas fa-chair")>] Chair
            | [<CompiledName("fas fa-chalkboard")>] Chalkboard
            | [<CompiledName("fas fa-chalkboard-teacher")>] ChalkboardTeacher
            | [<CompiledName("fas fa-charging-station")>] ChargingStation
            | [<CompiledName("fas fa-chart-area")>] ChartArea
            | [<CompiledName("fas fa-chart-bar")>] ChartBar
            | [<CompiledName("fas fa-chart-line")>] ChartLine
            | [<CompiledName("fas fa-chart-pie")>] ChartPie
            | [<CompiledName("fas fa-check")>] Check
            | [<CompiledName("fas fa-check-circle")>] CheckCircle
            | [<CompiledName("fas fa-check-double")>] CheckDouble
            | [<CompiledName("fas fa-check-square")>] CheckSquare
            | [<CompiledName("fas fa-chess")>] Chess
            | [<CompiledName("fas fa-chess-bishop")>] ChessBishop
            | [<CompiledName("fas fa-chess-board")>] ChessBoard
            | [<CompiledName("fas fa-chess-king")>] ChessKing
            | [<CompiledName("fas fa-chess-knight")>] ChessKnight
            | [<CompiledName("fas fa-chess-pawn")>] ChessPawn
            | [<CompiledName("fas fa-chess-queen")>] ChessQueen
            | [<CompiledName("fas fa-chess-rook")>] ChessRook
            | [<CompiledName("fas fa-chevron-circle-down")>] ChevronCircleDown
            | [<CompiledName("fas fa-chevron-circle-left")>] ChevronCircleLeft
            | [<CompiledName("fas fa-chevron-circle-right")>] ChevronCircleRight
            | [<CompiledName("fas fa-chevron-circle-up")>] ChevronCircleUp
            | [<CompiledName("fas fa-chevron-down")>] ChevronDown
            | [<CompiledName("fas fa-chevron-left")>] ChevronLeft
            | [<CompiledName("fas fa-chevron-right")>] ChevronRight
            | [<CompiledName("fas fa-chevron-up")>] ChevronUp
            | [<CompiledName("fas fa-child")>] Child
            | [<CompiledName("fas fa-church")>] Church
            | [<CompiledName("fas fa-circle")>] Circle
            | [<CompiledName("fas fa-circle-notch")>] CircleNotch
            | [<CompiledName("fas fa-city")>] City
            | [<CompiledName("fas fa-clipboard")>] Clipboard
            | [<CompiledName("fas fa-clipboard-check")>] ClipboardCheck
            | [<CompiledName("fas fa-clipboard-list")>] ClipboardList
            | [<CompiledName("fas fa-clock")>] Clock
            | [<CompiledName("fas fa-clone")>] Clone
            | [<CompiledName("fas fa-closed-captioning")>] ClosedCaptioning
            | [<CompiledName("fas fa-cloud")>] Cloud
            | [<CompiledName("fas fa-cloud-download-alt")>] CloudDownloadAlt
            | [<CompiledName("fas fa-cloud-moon")>] CloudMoon
            | [<CompiledName("fas fa-cloud-sun")>] CloudSun
            | [<CompiledName("fas fa-cloud-upload-alt")>] CloudUploadAlt
            | [<CompiledName("fas fa-cocktail")>] Cocktail
            | [<CompiledName("fas fa-code")>] Code
            | [<CompiledName("fas fa-code-branch")>] CodeBranch
            | [<CompiledName("fas fa-coffee")>] Coffee
            | [<CompiledName("fas fa-cog")>] Cog
            | [<CompiledName("fas fa-cogs")>] Cogs
            | [<CompiledName("fas fa-coins")>] Coins
            | [<CompiledName("fas fa-columns")>] Columns
            | [<CompiledName("fas fa-comment")>] Comment
            | [<CompiledName("fas fa-comment-alt")>] CommentAlt
            | [<CompiledName("fas fa-comment-dollar")>] CommentDollar
            | [<CompiledName("fas fa-comment-dots")>] CommentDots
            | [<CompiledName("fas fa-comment-slash")>] CommentSlash
            | [<CompiledName("fas fa-comments")>] Comments
            | [<CompiledName("fas fa-comments-dollar")>] CommentsDollar
            | [<CompiledName("fas fa-compact-disc")>] CompactDisc
            | [<CompiledName("fas fa-compass")>] Compass
            | [<CompiledName("fas fa-compress")>] Compress
            | [<CompiledName("fas fa-concierge-bell")>] ConciergeBell
            | [<CompiledName("fas fa-cookie")>] Cookie
            | [<CompiledName("fas fa-cookie-bite")>] CookieBite
            | [<CompiledName("fas fa-copy")>] Copy
            | [<CompiledName("fas fa-copyright")>] Copyright
            | [<CompiledName("fas fa-couch")>] Couch
            | [<CompiledName("fas fa-credit-card")>] CreditCard
            | [<CompiledName("fas fa-crop")>] Crop
            | [<CompiledName("fas fa-crop-alt")>] CropAlt
            | [<CompiledName("fas fa-cross")>] Cross
            | [<CompiledName("fas fa-crosshairs")>] Crosshairs
            | [<CompiledName("fas fa-crow")>] Crow
            | [<CompiledName("fas fa-crown")>] Crown
            | [<CompiledName("fas fa-cube")>] Cube
            | [<CompiledName("fas fa-cubes")>] Cubes
            | [<CompiledName("fas fa-cut")>] Cut
            | [<CompiledName("fas fa-database")>] Database
            | [<CompiledName("fas fa-deaf")>] Deaf
            | [<CompiledName("fas fa-desktop")>] Desktop
            | [<CompiledName("fas fa-dharmachakra")>] Dharmachakra
            | [<CompiledName("fas fa-diagnoses")>] Diagnoses
            | [<CompiledName("fas fa-dice")>] Dice
            | [<CompiledName("fas fa-dice-d20")>] DiceD20
            | [<CompiledName("fas fa-dice-d6")>] DiceD6
            | [<CompiledName("fas fa-dice-five")>] DiceFive
            | [<CompiledName("fas fa-dice-four")>] DiceFour
            | [<CompiledName("fas fa-dice-one")>] DiceOne
            | [<CompiledName("fas fa-dice-six")>] DiceSix
            | [<CompiledName("fas fa-dice-three")>] DiceThree
            | [<CompiledName("fas fa-dice-two")>] DiceTwo
            | [<CompiledName("fas fa-digital-tachograph")>] DigitalTachograph
            | [<CompiledName("fas fa-directions")>] Directions
            | [<CompiledName("fas fa-divide")>] Divide
            | [<CompiledName("fas fa-dizzy")>] Dizzy
            | [<CompiledName("fas fa-dna")>] Dna
            | [<CompiledName("fas fa-dog")>] Dog
            | [<CompiledName("fas fa-dollar-sign")>] DollarSign
            | [<CompiledName("fas fa-dolly")>] Dolly
            | [<CompiledName("fas fa-dolly-flatbed")>] DollyFlatbed
            | [<CompiledName("fas fa-donate")>] Donate
            | [<CompiledName("fas fa-door-closed")>] DoorClosed
            | [<CompiledName("fas fa-door-open")>] DoorOpen
            | [<CompiledName("fas fa-dot-circle")>] DotCircle
            | [<CompiledName("fas fa-dove")>] Dove
            | [<CompiledName("fas fa-download")>] Download
            | [<CompiledName("fas fa-drafting-compass")>] DraftingCompass
            | [<CompiledName("fas fa-dragon")>] Dragon
            | [<CompiledName("fas fa-draw-polygon")>] DrawPolygon
            | [<CompiledName("fas fa-drum")>] Drum
            | [<CompiledName("fas fa-drum-steelpan")>] DrumSteelpan
            | [<CompiledName("fas fa-drumstick-bite")>] DrumstickBite
            | [<CompiledName("fas fa-dumbbell")>] Dumbbell
            | [<CompiledName("fas fa-dungeon")>] Dungeon
            | [<CompiledName("fas fa-edit")>] Edit
            | [<CompiledName("fas fa-eject")>] Eject
            | [<CompiledName("fas fa-ellipsis-h")>] EllipsisH
            | [<CompiledName("fas fa-ellipsis-v")>] EllipsisV
            | [<CompiledName("fas fa-envelope")>] Envelope
            | [<CompiledName("fas fa-envelope-open")>] EnvelopeOpen
            | [<CompiledName("fas fa-envelope-open-text")>] EnvelopeOpenText
            | [<CompiledName("fas fa-envelope-square")>] EnvelopeSquare
            | [<CompiledName("fas fa-equals")>] Equals
            | [<CompiledName("fas fa-eraser")>] Eraser
            | [<CompiledName("fas fa-euro-sign")>] EuroSign
            | [<CompiledName("fas fa-exchange-alt")>] ExchangeAlt
            | [<CompiledName("fas fa-exclamation")>] Exclamation
            | [<CompiledName("fas fa-exclamation-circle")>] ExclamationCircle
            | [<CompiledName("fas fa-exclamation-triangle")>] ExclamationTriangle
            | [<CompiledName("fas fa-expand")>] Expand
            | [<CompiledName("fas fa-expand-arrows-alt")>] ExpandArrowsAlt
            | [<CompiledName("fas fa-external-link-alt")>] ExternalLinkAlt
            | [<CompiledName("fas fa-external-link-square-alt")>] ExternalLinkSquareAlt
            | [<CompiledName("fas fa-eye")>] Eye
            | [<CompiledName("fas fa-eye-dropper")>] EyeDropper
            | [<CompiledName("fas fa-eye-slash")>] EyeSlash
            | [<CompiledName("fas fa-fast-backward")>] FastBackward
            | [<CompiledName("fas fa-fast-forward")>] FastForward
            | [<CompiledName("fas fa-fax")>] Fax
            | [<CompiledName("fas fa-feather")>] Feather
            | [<CompiledName("fas fa-feather-alt")>] FeatherAlt
            | [<CompiledName("fas fa-female")>] Female
            | [<CompiledName("fas fa-fighter-jet")>] FighterJet
            | [<CompiledName("fas fa-file")>] File
            | [<CompiledName("fas fa-file-alt")>] FileAlt
            | [<CompiledName("fas fa-file-archive")>] FileArchive
            | [<CompiledName("fas fa-file-audio")>] FileAudio
            | [<CompiledName("fas fa-file-code")>] FileCode
            | [<CompiledName("fas fa-file-contract")>] FileContract
            | [<CompiledName("fas fa-file-csv")>] FileCsv
            | [<CompiledName("fas fa-file-download")>] FileDownload
            | [<CompiledName("fas fa-file-excel")>] FileExcel
            | [<CompiledName("fas fa-file-export")>] FileExport
            | [<CompiledName("fas fa-file-image")>] FileImage
            | [<CompiledName("fas fa-file-import")>] FileImport
            | [<CompiledName("fas fa-file-invoice")>] FileInvoice
            | [<CompiledName("fas fa-file-invoice-dollar")>] FileInvoiceDollar
            | [<CompiledName("fas fa-file-medical")>] FileMedical
            | [<CompiledName("fas fa-file-medical-alt")>] FileMedicalAlt
            | [<CompiledName("fas fa-file-pdf")>] FilePdf
            | [<CompiledName("fas fa-file-powerpoint")>] FilePowerpoint
            | [<CompiledName("fas fa-file-prescription")>] FilePrescription
            | [<CompiledName("fas fa-file-signature")>] FileSignature
            | [<CompiledName("fas fa-file-upload")>] FileUpload
            | [<CompiledName("fas fa-file-video")>] FileVideo
            | [<CompiledName("fas fa-file-word")>] FileWord
            | [<CompiledName("fas fa-fill")>] Fill
            | [<CompiledName("fas fa-fill-drip")>] FillDrip
            | [<CompiledName("fas fa-film")>] Film
            | [<CompiledName("fas fa-filter")>] Filter
            | [<CompiledName("fas fa-fingerprint")>] Fingerprint
            | [<CompiledName("fas fa-fire")>] Fire
            | [<CompiledName("fas fa-fire-extinguisher")>] FireExtinguisher
            | [<CompiledName("fas fa-first-aid")>] FirstAid
            | [<CompiledName("fas fa-fish")>] Fish
            | [<CompiledName("fas fa-fist-raised")>] FistRaised
            | [<CompiledName("fas fa-flag")>] Flag
            | [<CompiledName("fas fa-flag-checkered")>] FlagCheckered
            | [<CompiledName("fas fa-flask")>] Flask
            | [<CompiledName("fas fa-flushed")>] Flushed
            | [<CompiledName("fas fa-folder")>] Folder
            | [<CompiledName("fas fa-folder-minus")>] FolderMinus
            | [<CompiledName("fas fa-folder-open")>] FolderOpen
            | [<CompiledName("fas fa-folder-plus")>] FolderPlus
            | [<CompiledName("fas fa-font")>] Font
            | [<CompiledName("fas fa-font-awesome-logo-full")>] FontAwesomeLogoFull
            | [<CompiledName("fas fa-football-ball")>] FootballBall
            | [<CompiledName("fas fa-forward")>] Forward
            | [<CompiledName("fas fa-frog")>] Frog
            | [<CompiledName("fas fa-frown")>] Frown
            | [<CompiledName("fas fa-frown-open")>] FrownOpen
            | [<CompiledName("fas fa-funnel-dollar")>] FunnelDollar
            | [<CompiledName("fas fa-futbol")>] Futbol
            | [<CompiledName("fas fa-gamepad")>] Gamepad
            | [<CompiledName("fas fa-gas-pump")>] GasPump
            | [<CompiledName("fas fa-gavel")>] Gavel
            | [<CompiledName("fas fa-gem")>] Gem
            | [<CompiledName("fas fa-genderless")>] Genderless
            | [<CompiledName("fas fa-ghost")>] Ghost
            | [<CompiledName("fas fa-gift")>] Gift
            | [<CompiledName("fas fa-glass-martini")>] GlassMartini
            | [<CompiledName("fas fa-glass-martini-alt")>] GlassMartiniAlt
            | [<CompiledName("fas fa-glasses")>] Glasses
            | [<CompiledName("fas fa-globe")>] Globe
            | [<CompiledName("fas fa-globe-africa")>] GlobeAfrica
            | [<CompiledName("fas fa-globe-americas")>] GlobeAmericas
            | [<CompiledName("fas fa-globe-asia")>] GlobeAsia
            | [<CompiledName("fas fa-golf-ball")>] GolfBall
            | [<CompiledName("fas fa-gopuram")>] Gopuram
            | [<CompiledName("fas fa-graduation-cap")>] GraduationCap
            | [<CompiledName("fas fa-greater-than")>] GreaterThan
            | [<CompiledName("fas fa-greater-than-equal")>] GreaterThanEqual
            | [<CompiledName("fas fa-grimace")>] Grimace
            | [<CompiledName("fas fa-grin")>] Grin
            | [<CompiledName("fas fa-grin-alt")>] GrinAlt
            | [<CompiledName("fas fa-grin-beam")>] GrinBeam
            | [<CompiledName("fas fa-grin-beam-sweat")>] GrinBeamSweat
            | [<CompiledName("fas fa-grin-hearts")>] GrinHearts
            | [<CompiledName("fas fa-grin-squint")>] GrinSquint
            | [<CompiledName("fas fa-grin-squint-tears")>] GrinSquintTears
            | [<CompiledName("fas fa-grin-stars")>] GrinStars
            | [<CompiledName("fas fa-grin-tears")>] GrinTears
            | [<CompiledName("fas fa-grin-tongue")>] GrinTongue
            | [<CompiledName("fas fa-grin-tongue-squint")>] GrinTongueSquint
            | [<CompiledName("fas fa-grin-tongue-wink")>] GrinTongueWink
            | [<CompiledName("fas fa-grin-wink")>] GrinWink
            | [<CompiledName("fas fa-grip-horizontal")>] GripHorizontal
            | [<CompiledName("fas fa-grip-vertical")>] GripVertical
            | [<CompiledName("fas fa-h-square")>] HSquare
            | [<CompiledName("fas fa-hammer")>] Hammer
            | [<CompiledName("fas fa-hamsa")>] Hamsa
            | [<CompiledName("fas fa-hand-holding")>] HandHolding
            | [<CompiledName("fas fa-hand-holding-heart")>] HandHoldingHeart
            | [<CompiledName("fas fa-hand-holding-usd")>] HandHoldingUsd
            | [<CompiledName("fas fa-hand-lizard")>] HandLizard
            | [<CompiledName("fas fa-hand-paper")>] HandPaper
            | [<CompiledName("fas fa-hand-peace")>] HandPeace
            | [<CompiledName("fas fa-hand-point-down")>] HandPointDown
            | [<CompiledName("fas fa-hand-point-left")>] HandPointLeft
            | [<CompiledName("fas fa-hand-point-right")>] HandPointRight
            | [<CompiledName("fas fa-hand-point-up")>] HandPointUp
            | [<CompiledName("fas fa-hand-pointer")>] HandPointer
            | [<CompiledName("fas fa-hand-rock")>] HandRock
            | [<CompiledName("fas fa-hand-scissors")>] HandScissors
            | [<CompiledName("fas fa-hand-spock")>] HandSpock
            | [<CompiledName("fas fa-hands")>] Hands
            | [<CompiledName("fas fa-hands-helping")>] HandsHelping
            | [<CompiledName("fas fa-handshake")>] Handshake
            | [<CompiledName("fas fa-hanukiah")>] Hanukiah
            | [<CompiledName("fas fa-hashtag")>] Hashtag
            | [<CompiledName("fas fa-hat-wizard")>] HatWizard
            | [<CompiledName("fas fa-haykal")>] Haykal
            | [<CompiledName("fas fa-hdd")>] Hdd
            | [<CompiledName("fas fa-heading")>] Heading
            | [<CompiledName("fas fa-headphones")>] Headphones
            | [<CompiledName("fas fa-headphones-alt")>] HeadphonesAlt
            | [<CompiledName("fas fa-headset")>] Headset
            | [<CompiledName("fas fa-heart")>] Heart
            | [<CompiledName("fas fa-heartbeat")>] Heartbeat
            | [<CompiledName("fas fa-helicopter")>] Helicopter
            | [<CompiledName("fas fa-highlighter")>] Highlighter
            | [<CompiledName("fas fa-hiking")>] Hiking
            | [<CompiledName("fas fa-hippo")>] Hippo
            | [<CompiledName("fas fa-history")>] History
            | [<CompiledName("fas fa-hockey-puck")>] HockeyPuck
            | [<CompiledName("fas fa-home")>] Home
            | [<CompiledName("fas fa-horse")>] Horse
            | [<CompiledName("fas fa-hospital")>] Hospital
            | [<CompiledName("fas fa-hospital-alt")>] HospitalAlt
            | [<CompiledName("fas fa-hospital-symbol")>] HospitalSymbol
            | [<CompiledName("fas fa-hot-tub")>] HotTub
            | [<CompiledName("fas fa-hotel")>] Hotel
            | [<CompiledName("fas fa-hourglass")>] Hourglass
            | [<CompiledName("fas fa-hourglass-end")>] HourglassEnd
            | [<CompiledName("fas fa-hourglass-half")>] HourglassHalf
            | [<CompiledName("fas fa-hourglass-start")>] HourglassStart
            | [<CompiledName("fas fa-house-damage")>] HouseDamage
            | [<CompiledName("fas fa-hryvnia")>] Hryvnia
            | [<CompiledName("fas fa-i-cursor")>] ICursor
            | [<CompiledName("fas fa-id-badge")>] IdBadge
            | [<CompiledName("fas fa-id-card")>] IdCard
            | [<CompiledName("fas fa-id-card-alt")>] IdCardAlt
            | [<CompiledName("fas fa-image")>] Image
            | [<CompiledName("fas fa-images")>] Images
            | [<CompiledName("fas fa-inbox")>] Inbox
            | [<CompiledName("fas fa-indent")>] Indent
            | [<CompiledName("fas fa-industry")>] Industry
            | [<CompiledName("fas fa-infinity")>] Infinity
            | [<CompiledName("fas fa-info")>] Info
            | [<CompiledName("fas fa-info-circle")>] InfoCircle
            | [<CompiledName("fas fa-italic")>] Italic
            | [<CompiledName("fas fa-jedi")>] Jedi
            | [<CompiledName("fas fa-joint")>] Joint
            | [<CompiledName("fas fa-journal-whills")>] JournalWhills
            | [<CompiledName("fas fa-kaaba")>] Kaaba
            | [<CompiledName("fas fa-key")>] Key
            | [<CompiledName("fas fa-keyboard")>] Keyboard
            | [<CompiledName("fas fa-khanda")>] Khanda
            | [<CompiledName("fas fa-kiss")>] Kiss
            | [<CompiledName("fas fa-kiss-beam")>] KissBeam
            | [<CompiledName("fas fa-kiss-wink-heart")>] KissWinkHeart
            | [<CompiledName("fas fa-kiwi-bird")>] KiwiBird
            | [<CompiledName("fas fa-landmark")>] Landmark
            | [<CompiledName("fas fa-language")>] Language
            | [<CompiledName("fas fa-laptop")>] Laptop
            | [<CompiledName("fas fa-laptop-code")>] LaptopCode
            | [<CompiledName("fas fa-laugh")>] Laugh
            | [<CompiledName("fas fa-laugh-beam")>] LaughBeam
            | [<CompiledName("fas fa-laugh-squint")>] LaughSquint
            | [<CompiledName("fas fa-laugh-wink")>] LaughWink
            | [<CompiledName("fas fa-layer-group")>] LayerGroup
            | [<CompiledName("fas fa-leaf")>] Leaf
            | [<CompiledName("fas fa-lemon")>] Lemon
            | [<CompiledName("fas fa-less-than")>] LessThan
            | [<CompiledName("fas fa-less-than-equal")>] LessThanEqual
            | [<CompiledName("fas fa-level-down-alt")>] LevelDownAlt
            | [<CompiledName("fas fa-level-up-alt")>] LevelUpAlt
            | [<CompiledName("fas fa-life-ring")>] LifeRing
            | [<CompiledName("fas fa-lightbulb")>] Lightbulb
            | [<CompiledName("fas fa-link")>] Link
            | [<CompiledName("fas fa-lira-sign")>] LiraSign
            | [<CompiledName("fas fa-list")>] List
            | [<CompiledName("fas fa-list-alt")>] ListAlt
            | [<CompiledName("fas fa-list-ol")>] ListOl
            | [<CompiledName("fas fa-list-ul")>] ListUl
            | [<CompiledName("fas fa-location-arrow")>] LocationArrow
            | [<CompiledName("fas fa-lock")>] Lock
            | [<CompiledName("fas fa-lock-open")>] LockOpen
            | [<CompiledName("fas fa-long-arrow-alt-down")>] LongArrowAltDown
            | [<CompiledName("fas fa-long-arrow-alt-left")>] LongArrowAltLeft
            | [<CompiledName("fas fa-long-arrow-alt-right")>] LongArrowAltRight
            | [<CompiledName("fas fa-long-arrow-alt-up")>] LongArrowAltUp
            | [<CompiledName("fas fa-low-vision")>] LowVision
            | [<CompiledName("fas fa-luggage-cart")>] LuggageCart
            | [<CompiledName("fas fa-magic")>] Magic
            | [<CompiledName("fas fa-magnet")>] Magnet
            | [<CompiledName("fas fa-mail-bulk")>] MailBulk
            | [<CompiledName("fas fa-male")>] Male
            | [<CompiledName("fas fa-map")>] Map
            | [<CompiledName("fas fa-map-marked")>] MapMarked
            | [<CompiledName("fas fa-map-marked-alt")>] MapMarkedAlt
            | [<CompiledName("fas fa-map-marker")>] MapMarker
            | [<CompiledName("fas fa-map-marker-alt")>] MapMarkerAlt
            | [<CompiledName("fas fa-map-pin")>] MapPin
            | [<CompiledName("fas fa-map-signs")>] MapSigns
            | [<CompiledName("fas fa-marker")>] Marker
            | [<CompiledName("fas fa-mars")>] Mars
            | [<CompiledName("fas fa-mars-double")>] MarsDouble
            | [<CompiledName("fas fa-mars-stroke")>] MarsStroke
            | [<CompiledName("fas fa-mars-stroke-h")>] MarsStrokeH
            | [<CompiledName("fas fa-mars-stroke-v")>] MarsStrokeV
            | [<CompiledName("fas fa-mask")>] Mask
            | [<CompiledName("fas fa-medal")>] Medal
            | [<CompiledName("fas fa-medkit")>] Medkit
            | [<CompiledName("fas fa-meh")>] Meh
            | [<CompiledName("fas fa-meh-blank")>] MehBlank
            | [<CompiledName("fas fa-meh-rolling-eyes")>] MehRollingEyes
            | [<CompiledName("fas fa-memory")>] Memory
            | [<CompiledName("fas fa-menorah")>] Menorah
            | [<CompiledName("fas fa-mercury")>] Mercury
            | [<CompiledName("fas fa-microchip")>] Microchip
            | [<CompiledName("fas fa-microphone")>] Microphone
            | [<CompiledName("fas fa-microphone-alt")>] MicrophoneAlt
            | [<CompiledName("fas fa-microphone-alt-slash")>] MicrophoneAltSlash
            | [<CompiledName("fas fa-microphone-slash")>] MicrophoneSlash
            | [<CompiledName("fas fa-microscope")>] Microscope
            | [<CompiledName("fas fa-minus")>] Minus
            | [<CompiledName("fas fa-minus-circle")>] MinusCircle
            | [<CompiledName("fas fa-minus-square")>] MinusSquare
            | [<CompiledName("fas fa-mobile")>] Mobile
            | [<CompiledName("fas fa-mobile-alt")>] MobileAlt
            | [<CompiledName("fas fa-money-bill")>] MoneyBill
            | [<CompiledName("fas fa-money-bill-alt")>] MoneyBillAlt
            | [<CompiledName("fas fa-money-bill-wave")>] MoneyBillWave
            | [<CompiledName("fas fa-money-bill-wave-alt")>] MoneyBillWaveAlt
            | [<CompiledName("fas fa-money-check")>] MoneyCheck
            | [<CompiledName("fas fa-money-check-alt")>] MoneyCheckAlt
            | [<CompiledName("fas fa-monument")>] Monument
            | [<CompiledName("fas fa-moon")>] Moon
            | [<CompiledName("fas fa-mortar-pestle")>] MortarPestle
            | [<CompiledName("fas fa-mosque")>] Mosque
            | [<CompiledName("fas fa-motorcycle")>] Motorcycle
            | [<CompiledName("fas fa-mountain")>] Mountain
            | [<CompiledName("fas fa-mouse-pointer")>] MousePointer
            | [<CompiledName("fas fa-music")>] Music
            | [<CompiledName("fas fa-network-wired")>] NetworkWired
            | [<CompiledName("fas fa-neuter")>] Neuter
            | [<CompiledName("fas fa-newspaper")>] Newspaper
            | [<CompiledName("fas fa-not-equal")>] NotEqual
            | [<CompiledName("fas fa-notes-medical")>] NotesMedical
            | [<CompiledName("fas fa-object-group")>] ObjectGroup
            | [<CompiledName("fas fa-object-ungroup")>] ObjectUngroup
            | [<CompiledName("fas fa-oil-can")>] OilCan
            | [<CompiledName("fas fa-om")>] Om
            | [<CompiledName("fas fa-otter")>] Otter
            | [<CompiledName("fas fa-outdent")>] Outdent
            | [<CompiledName("fas fa-paint-brush")>] PaintBrush
            | [<CompiledName("fas fa-paint-roller")>] PaintRoller
            | [<CompiledName("fas fa-palette")>] Palette
            | [<CompiledName("fas fa-pallet")>] Pallet
            | [<CompiledName("fas fa-paper-plane")>] PaperPlane
            | [<CompiledName("fas fa-paperclip")>] Paperclip
            | [<CompiledName("fas fa-parachute-box")>] ParachuteBox
            | [<CompiledName("fas fa-paragraph")>] Paragraph
            | [<CompiledName("fas fa-parking")>] Parking
            | [<CompiledName("fas fa-passport")>] Passport
            | [<CompiledName("fas fa-pastafarianism")>] Pastafarianism
            | [<CompiledName("fas fa-paste")>] Paste
            | [<CompiledName("fas fa-pause")>] Pause
            | [<CompiledName("fas fa-pause-circle")>] PauseCircle
            | [<CompiledName("fas fa-paw")>] Paw
            | [<CompiledName("fas fa-peace")>] Peace
            | [<CompiledName("fas fa-pen")>] Pen
            | [<CompiledName("fas fa-pen-alt")>] PenAlt
            | [<CompiledName("fas fa-pen-fancy")>] PenFancy
            | [<CompiledName("fas fa-pen-nib")>] PenNib
            | [<CompiledName("fas fa-pen-square")>] PenSquare
            | [<CompiledName("fas fa-pencil-alt")>] PencilAlt
            | [<CompiledName("fas fa-pencil-ruler")>] PencilRuler
            | [<CompiledName("fas fa-people-carry")>] PeopleCarry
            | [<CompiledName("fas fa-percent")>] Percent
            | [<CompiledName("fas fa-percentage")>] Percentage
            | [<CompiledName("fas fa-phone")>] Phone
            | [<CompiledName("fas fa-phone-slash")>] PhoneSlash
            | [<CompiledName("fas fa-phone-square")>] PhoneSquare
            | [<CompiledName("fas fa-phone-volume")>] PhoneVolume
            | [<CompiledName("fas fa-piggy-bank")>] PiggyBank
            | [<CompiledName("fas fa-pills")>] Pills
            | [<CompiledName("fas fa-place-of-worship")>] PlaceOfWorship
            | [<CompiledName("fas fa-plane")>] Plane
            | [<CompiledName("fas fa-plane-arrival")>] PlaneArrival
            | [<CompiledName("fas fa-plane-departure")>] PlaneDeparture
            | [<CompiledName("fas fa-play")>] Play
            | [<CompiledName("fas fa-play-circle")>] PlayCircle
            | [<CompiledName("fas fa-plug")>] Plug
            | [<CompiledName("fas fa-plus")>] Plus
            | [<CompiledName("fas fa-plus-circle")>] PlusCircle
            | [<CompiledName("fas fa-plus-square")>] PlusSquare
            | [<CompiledName("fas fa-podcast")>] Podcast
            | [<CompiledName("fas fa-poll")>] Poll
            | [<CompiledName("fas fa-poll-h")>] PollH
            | [<CompiledName("fas fa-poo")>] Poo
            | [<CompiledName("fas fa-poop")>] Poop
            | [<CompiledName("fas fa-portrait")>] Portrait
            | [<CompiledName("fas fa-pound-sign")>] PoundSign
            | [<CompiledName("fas fa-power-off")>] PowerOff
            | [<CompiledName("fas fa-pray")>] Pray
            | [<CompiledName("fas fa-praying-hands")>] PrayingHands
            | [<CompiledName("fas fa-prescription")>] Prescription
            | [<CompiledName("fas fa-prescription-bottle")>] PrescriptionBottle
            | [<CompiledName("fas fa-prescription-bottle-alt")>] PrescriptionBottleAlt
            | [<CompiledName("fas fa-print")>] Print
            | [<CompiledName("fas fa-procedures")>] Procedures
            | [<CompiledName("fas fa-project-diagram")>] ProjectDiagram
            | [<CompiledName("fas fa-puzzle-piece")>] PuzzlePiece
            | [<CompiledName("fas fa-qrcode")>] Qrcode
            | [<CompiledName("fas fa-question")>] Question
            | [<CompiledName("fas fa-question-circle")>] QuestionCircle
            | [<CompiledName("fas fa-quidditch")>] Quidditch
            | [<CompiledName("fas fa-quote-left")>] QuoteLeft
            | [<CompiledName("fas fa-quote-right")>] QuoteRight
            | [<CompiledName("fas fa-quran")>] Quran
            | [<CompiledName("fas fa-random")>] Random
            | [<CompiledName("fas fa-receipt")>] Receipt
            | [<CompiledName("fas fa-recycle")>] Recycle
            | [<CompiledName("fas fa-redo")>] Redo
            | [<CompiledName("fas fa-redo-alt")>] RedoAlt
            | [<CompiledName("fas fa-registered")>] Registered
            | [<CompiledName("fas fa-reply")>] Reply
            | [<CompiledName("fas fa-reply-all")>] ReplyAll
            | [<CompiledName("fas fa-retweet")>] Retweet
            | [<CompiledName("fas fa-ribbon")>] Ribbon
            | [<CompiledName("fas fa-ring")>] Ring
            | [<CompiledName("fas fa-road")>] Road
            | [<CompiledName("fas fa-robot")>] Robot
            | [<CompiledName("fas fa-rocket")>] Rocket
            | [<CompiledName("fas fa-route")>] Route
            | [<CompiledName("fas fa-rss")>] Rss
            | [<CompiledName("fas fa-rss-square")>] RssSquare
            | [<CompiledName("fas fa-ruble-sign")>] RubleSign
            | [<CompiledName("fas fa-ruler")>] Ruler
            | [<CompiledName("fas fa-ruler-combined")>] RulerCombined
            | [<CompiledName("fas fa-ruler-horizontal")>] RulerHorizontal
            | [<CompiledName("fas fa-ruler-vertical")>] RulerVertical
            | [<CompiledName("fas fa-running")>] Running
            | [<CompiledName("fas fa-rupee-sign")>] RupeeSign
            | [<CompiledName("fas fa-sad-cry")>] SadCry
            | [<CompiledName("fas fa-sad-tear")>] SadTear
            | [<CompiledName("fas fa-save")>] Save
            | [<CompiledName("fas fa-school")>] School
            | [<CompiledName("fas fa-screwdriver")>] Screwdriver
            | [<CompiledName("fas fa-scroll")>] Scroll
            | [<CompiledName("fas fa-search")>] Search
            | [<CompiledName("fas fa-search-dollar")>] SearchDollar
            | [<CompiledName("fas fa-search-location")>] SearchLocation
            | [<CompiledName("fas fa-search-minus")>] SearchMinus
            | [<CompiledName("fas fa-search-plus")>] SearchPlus
            | [<CompiledName("fas fa-seedling")>] Seedling
            | [<CompiledName("fas fa-server")>] Server
            | [<CompiledName("fas fa-shapes")>] Shapes
            | [<CompiledName("fas fa-share")>] Share
            | [<CompiledName("fas fa-share-alt")>] ShareAlt
            | [<CompiledName("fas fa-share-alt-square")>] ShareAltSquare
            | [<CompiledName("fas fa-share-square")>] ShareSquare
            | [<CompiledName("fas fa-shekel-sign")>] ShekelSign
            | [<CompiledName("fas fa-shield-alt")>] ShieldAlt
            | [<CompiledName("fas fa-ship")>] Ship
            | [<CompiledName("fas fa-shipping-fast")>] ShippingFast
            | [<CompiledName("fas fa-shoe-prints")>] ShoePrints
            | [<CompiledName("fas fa-shopping-bag")>] ShoppingBag
            | [<CompiledName("fas fa-shopping-basket")>] ShoppingBasket
            | [<CompiledName("fas fa-shopping-cart")>] ShoppingCart
            | [<CompiledName("fas fa-shower")>] Shower
            | [<CompiledName("fas fa-shuttle-van")>] ShuttleVan
            | [<CompiledName("fas fa-sign")>] Sign
            | [<CompiledName("fas fa-sign-in-alt")>] SignInAlt
            | [<CompiledName("fas fa-sign-language")>] SignLanguage
            | [<CompiledName("fas fa-sign-out-alt")>] SignOutAlt
            | [<CompiledName("fas fa-signal")>] Signal
            | [<CompiledName("fas fa-signature")>] Signature
            | [<CompiledName("fas fa-sitemap")>] Sitemap
            | [<CompiledName("fas fa-skull")>] Skull
            | [<CompiledName("fas fa-skull-crossbones")>] SkullCrossbones
            | [<CompiledName("fas fa-slash")>] Slash
            | [<CompiledName("fas fa-sliders-h")>] SlidersH
            | [<CompiledName("fas fa-smile")>] Smile
            | [<CompiledName("fas fa-smile-beam")>] SmileBeam
            | [<CompiledName("fas fa-smile-wink")>] SmileWink
            | [<CompiledName("fas fa-smoking")>] Smoking
            | [<CompiledName("fas fa-smoking-ban")>] SmokingBan
            | [<CompiledName("fas fa-snowflake")>] Snowflake
            | [<CompiledName("fas fa-socks")>] Socks
            | [<CompiledName("fas fa-solar-panel")>] SolarPanel
            | [<CompiledName("fas fa-sort")>] Sort
            | [<CompiledName("fas fa-sort-alpha-down")>] SortAlphaDown
            | [<CompiledName("fas fa-sort-alpha-up")>] SortAlphaUp
            | [<CompiledName("fas fa-sort-amount-down")>] SortAmountDown
            | [<CompiledName("fas fa-sort-amount-up")>] SortAmountUp
            | [<CompiledName("fas fa-sort-down")>] SortDown
            | [<CompiledName("fas fa-sort-numeric-down")>] SortNumericDown
            | [<CompiledName("fas fa-sort-numeric-up")>] SortNumericUp
            | [<CompiledName("fas fa-sort-up")>] SortUp
            | [<CompiledName("fas fa-spa")>] Spa
            | [<CompiledName("fas fa-space-shuttle")>] SpaceShuttle
            | [<CompiledName("fas fa-spider")>] Spider
            | [<CompiledName("fas fa-spinner")>] Spinner
            | [<CompiledName("fas fa-splotch")>] Splotch
            | [<CompiledName("fas fa-spray-can")>] SprayCan
            | [<CompiledName("fas fa-square")>] Square
            | [<CompiledName("fas fa-square-full")>] SquareFull
            | [<CompiledName("fas fa-square-root-alt")>] SquareRootAlt
            | [<CompiledName("fas fa-stamp")>] Stamp
            | [<CompiledName("fas fa-star")>] Star
            | [<CompiledName("fas fa-star-and-crescent")>] StarAndCrescent
            | [<CompiledName("fas fa-star-half")>] StarHalf
            | [<CompiledName("fas fa-star-half-alt")>] StarHalfAlt
            | [<CompiledName("fas fa-star-of-david")>] StarOfDavid
            | [<CompiledName("fas fa-star-of-life")>] StarOfLife
            | [<CompiledName("fas fa-step-backward")>] StepBackward
            | [<CompiledName("fas fa-step-forward")>] StepForward
            | [<CompiledName("fas fa-stethoscope")>] Stethoscope
            | [<CompiledName("fas fa-sticky-note")>] StickyNote
            | [<CompiledName("fas fa-stop")>] Stop
            | [<CompiledName("fas fa-stop-circle")>] StopCircle
            | [<CompiledName("fas fa-stopwatch")>] Stopwatch
            | [<CompiledName("fas fa-store")>] Store
            | [<CompiledName("fas fa-store-alt")>] StoreAlt
            | [<CompiledName("fas fa-stream")>] Stream
            | [<CompiledName("fas fa-street-view")>] StreetView
            | [<CompiledName("fas fa-strikethrough")>] Strikethrough
            | [<CompiledName("fas fa-stroopwafel")>] Stroopwafel
            | [<CompiledName("fas fa-subscript")>] Subscript
            | [<CompiledName("fas fa-subway")>] Subway
            | [<CompiledName("fas fa-suitcase")>] Suitcase
            | [<CompiledName("fas fa-suitcase-rolling")>] SuitcaseRolling
            | [<CompiledName("fas fa-sun")>] Sun
            | [<CompiledName("fas fa-superscript")>] Superscript
            | [<CompiledName("fas fa-surprise")>] Surprise
            | [<CompiledName("fas fa-swatchbook")>] Swatchbook
            | [<CompiledName("fas fa-swimmer")>] Swimmer
            | [<CompiledName("fas fa-swimming-pool")>] SwimmingPool
            | [<CompiledName("fas fa-synagogue")>] Synagogue
            | [<CompiledName("fas fa-sync")>] Sync
            | [<CompiledName("fas fa-sync-alt")>] SyncAlt
            | [<CompiledName("fas fa-syringe")>] Syringe
            | [<CompiledName("fas fa-table")>] Table
            | [<CompiledName("fas fa-table-tennis")>] TableTennis
            | [<CompiledName("fas fa-tablet")>] Tablet
            | [<CompiledName("fas fa-tablet-alt")>] TabletAlt
            | [<CompiledName("fas fa-tablets")>] Tablets
            | [<CompiledName("fas fa-tachometer-alt")>] TachometerAlt
            | [<CompiledName("fas fa-tag")>] Tag
            | [<CompiledName("fas fa-tags")>] Tags
            | [<CompiledName("fas fa-tape")>] Tape
            | [<CompiledName("fas fa-tasks")>] Tasks
            | [<CompiledName("fas fa-taxi")>] Taxi
            | [<CompiledName("fas fa-teeth")>] Teeth
            | [<CompiledName("fas fa-teeth-open")>] TeethOpen
            | [<CompiledName("fas fa-terminal")>] Terminal
            | [<CompiledName("fas fa-text-height")>] TextHeight
            | [<CompiledName("fas fa-text-width")>] TextWidth
            | [<CompiledName("fas fa-th")>] Th
            | [<CompiledName("fas fa-th-large")>] ThLarge
            | [<CompiledName("fas fa-th-list")>] ThList
            | [<CompiledName("fas fa-theater-masks")>] TheaterMasks
            | [<CompiledName("fas fa-thermometer")>] Thermometer
            | [<CompiledName("fas fa-thermometer-empty")>] ThermometerEmpty
            | [<CompiledName("fas fa-thermometer-full")>] ThermometerFull
            | [<CompiledName("fas fa-thermometer-half")>] ThermometerHalf
            | [<CompiledName("fas fa-thermometer-quarter")>] ThermometerQuarter
            | [<CompiledName("fas fa-thermometer-three-quarters")>] ThermometerThreeQuarters
            | [<CompiledName("fas fa-thumbs-down")>] ThumbsDown
            | [<CompiledName("fas fa-thumbs-up")>] ThumbsUp
            | [<CompiledName("fas fa-thumbtack")>] Thumbtack
            | [<CompiledName("fas fa-ticket-alt")>] TicketAlt
            | [<CompiledName("fas fa-times")>] Times
            | [<CompiledName("fas fa-times-circle")>] TimesCircle
            | [<CompiledName("fas fa-tint")>] Tint
            | [<CompiledName("fas fa-tint-slash")>] TintSlash
            | [<CompiledName("fas fa-tired")>] Tired
            | [<CompiledName("fas fa-toggle-off")>] ToggleOff
            | [<CompiledName("fas fa-toggle-on")>] ToggleOn
            | [<CompiledName("fas fa-toilet-paper")>] ToiletPaper
            | [<CompiledName("fas fa-toolbox")>] Toolbox
            | [<CompiledName("fas fa-tooth")>] Tooth
            | [<CompiledName("fas fa-torah")>] Torah
            | [<CompiledName("fas fa-torii-gate")>] ToriiGate
            | [<CompiledName("fas fa-tractor")>] Tractor
            | [<CompiledName("fas fa-trademark")>] Trademark
            | [<CompiledName("fas fa-traffic-light")>] TrafficLight
            | [<CompiledName("fas fa-train")>] Train
            | [<CompiledName("fas fa-transgender")>] Transgender
            | [<CompiledName("fas fa-transgender-alt")>] TransgenderAlt
            | [<CompiledName("fas fa-trash")>] Trash
            | [<CompiledName("fas fa-trash-alt")>] TrashAlt
            | [<CompiledName("fas fa-tree")>] Tree
            | [<CompiledName("fas fa-trophy")>] Trophy
            | [<CompiledName("fas fa-truck")>] Truck
            | [<CompiledName("fas fa-truck-loading")>] TruckLoading
            | [<CompiledName("fas fa-truck-monster")>] TruckMonster
            | [<CompiledName("fas fa-truck-moving")>] TruckMoving
            | [<CompiledName("fas fa-truck-pickup")>] TruckPickup
            | [<CompiledName("fas fa-tshirt")>] Tshirt
            | [<CompiledName("fas fa-tty")>] Tty
            | [<CompiledName("fas fa-tv")>] Tv
            | [<CompiledName("fas fa-umbrella")>] Umbrella
            | [<CompiledName("fas fa-umbrella-beach")>] UmbrellaBeach
            | [<CompiledName("fas fa-underline")>] Underline
            | [<CompiledName("fas fa-undo")>] Undo
            | [<CompiledName("fas fa-undo-alt")>] UndoAlt
            | [<CompiledName("fas fa-universal-access")>] UniversalAccess
            | [<CompiledName("fas fa-university")>] University
            | [<CompiledName("fas fa-unlink")>] Unlink
            | [<CompiledName("fas fa-unlock")>] Unlock
            | [<CompiledName("fas fa-unlock-alt")>] UnlockAlt
            | [<CompiledName("fas fa-upload")>] Upload
            | [<CompiledName("fas fa-user")>] User
            | [<CompiledName("fas fa-user-alt")>] UserAlt
            | [<CompiledName("fas fa-user-alt-slash")>] UserAltSlash
            | [<CompiledName("fas fa-user-astronaut")>] UserAstronaut
            | [<CompiledName("fas fa-user-check")>] UserCheck
            | [<CompiledName("fas fa-user-circle")>] UserCircle
            | [<CompiledName("fas fa-user-clock")>] UserClock
            | [<CompiledName("fas fa-user-cog")>] UserCog
            | [<CompiledName("fas fa-user-edit")>] UserEdit
            | [<CompiledName("fas fa-user-friends")>] UserFriends
            | [<CompiledName("fas fa-user-graduate")>] UserGraduate
            | [<CompiledName("fas fa-user-injured")>] UserInjured
            | [<CompiledName("fas fa-user-lock")>] UserLock
            | [<CompiledName("fas fa-user-md")>] UserMd
            | [<CompiledName("fas fa-user-minus")>] UserMinus
            | [<CompiledName("fas fa-user-ninja")>] UserNinja
            | [<CompiledName("fas fa-user-plus")>] UserPlus
            | [<CompiledName("fas fa-user-secret")>] UserSecret
            | [<CompiledName("fas fa-user-shield")>] UserShield
            | [<CompiledName("fas fa-user-slash")>] UserSlash
            | [<CompiledName("fas fa-user-tag")>] UserTag
            | [<CompiledName("fas fa-user-tie")>] UserTie
            | [<CompiledName("fas fa-user-times")>] UserTimes
            | [<CompiledName("fas fa-users")>] Users
            | [<CompiledName("fas fa-users-cog")>] UsersCog
            | [<CompiledName("fas fa-utensil-spoon")>] UtensilSpoon
            | [<CompiledName("fas fa-utensils")>] Utensils
            | [<CompiledName("fas fa-vector-square")>] VectorSquare
            | [<CompiledName("fas fa-venus")>] Venus
            | [<CompiledName("fas fa-venus-double")>] VenusDouble
            | [<CompiledName("fas fa-venus-mars")>] VenusMars
            | [<CompiledName("fas fa-vial")>] Vial
            | [<CompiledName("fas fa-vials")>] Vials
            | [<CompiledName("fas fa-video")>] Video
            | [<CompiledName("fas fa-video-slash")>] VideoSlash
            | [<CompiledName("fas fa-vihara")>] Vihara
            | [<CompiledName("fas fa-volleyball-ball")>] VolleyballBall
            | [<CompiledName("fas fa-volume-down")>] VolumeDown
            | [<CompiledName("fas fa-volume-mute")>] VolumeMute
            | [<CompiledName("fas fa-volume-off")>] VolumeOff
            | [<CompiledName("fas fa-volume-up")>] VolumeUp
            | [<CompiledName("fas fa-vr-cardboard")>] VrCardboard
            | [<CompiledName("fas fa-walking")>] Walking
            | [<CompiledName("fas fa-wallet")>] Wallet
            | [<CompiledName("fas fa-warehouse")>] Warehouse
            | [<CompiledName("fas fa-weight")>] Weight
            | [<CompiledName("fas fa-weight-hanging")>] WeightHanging
            | [<CompiledName("fas fa-wheelchair")>] Wheelchair
            | [<CompiledName("fas fa-wifi")>] Wifi
            | [<CompiledName("fas fa-wind")>] Wind
            | [<CompiledName("fas fa-window-close")>] WindowClose
            | [<CompiledName("fas fa-window-maximize")>] WindowMaximize
            | [<CompiledName("fas fa-window-minimize")>] WindowMinimize
            | [<CompiledName("fas fa-window-restore")>] WindowRestore
            | [<CompiledName("fas fa-wine-bottle")>] WineBottle
            | [<CompiledName("fas fa-wine-glass")>] WineGlass
            | [<CompiledName("fas fa-wine-glass-alt")>] WineGlassAlt
            | [<CompiledName("fas fa-won-sign")>] WonSign
            | [<CompiledName("fas fa-wrench")>] Wrench
            | [<CompiledName("fas fa-x-ray")>] XRay
            | [<CompiledName("fas fa-yen-sign")>] YenSign
            | [<CompiledName("fas fa-yin-yang")>] YinYang

        [<StringEnum>]
        type Regular =
            | [<CompiledName("far fa-address-book")>] AddressBook
            | [<CompiledName("far fa-address-card")>] AddressCard
            | [<CompiledName("far fa-angry")>] Angry
            | [<CompiledName("far fa-arrow-alt-circle-down")>] ArrowAltCircleDown
            | [<CompiledName("far fa-arrow-alt-circle-left")>] ArrowAltCircleLeft
            | [<CompiledName("far fa-arrow-alt-circle-right")>] ArrowAltCircleRight
            | [<CompiledName("far fa-arrow-alt-circle-up")>] ArrowAltCircleUp
            | [<CompiledName("far fa-bell")>] Bell
            | [<CompiledName("far fa-bell-slash")>] BellSlash
            | [<CompiledName("far fa-bookmark")>] Bookmark
            | [<CompiledName("far fa-building")>] Building
            | [<CompiledName("far fa-calendar")>] Calendar
            | [<CompiledName("far fa-calendar-alt")>] CalendarAlt
            | [<CompiledName("far fa-calendar-check")>] CalendarCheck
            | [<CompiledName("far fa-calendar-minus")>] CalendarMinus
            | [<CompiledName("far fa-calendar-plus")>] CalendarPlus
            | [<CompiledName("far fa-calendar-times")>] CalendarTimes
            | [<CompiledName("far fa-caret-square-down")>] CaretSquareDown
            | [<CompiledName("far fa-caret-square-left")>] CaretSquareLeft
            | [<CompiledName("far fa-caret-square-right")>] CaretSquareRight
            | [<CompiledName("far fa-caret-square-up")>] CaretSquareUp
            | [<CompiledName("far fa-chart-bar")>] ChartBar
            | [<CompiledName("far fa-check-circle")>] CheckCircle
            | [<CompiledName("far fa-check-square")>] CheckSquare
            | [<CompiledName("far fa-circle")>] Circle
            | [<CompiledName("far fa-clipboard")>] Clipboard
            | [<CompiledName("far fa-clock")>] Clock
            | [<CompiledName("far fa-clone")>] Clone
            | [<CompiledName("far fa-closed-captioning")>] ClosedCaptioning
            | [<CompiledName("far fa-comment")>] Comment
            | [<CompiledName("far fa-comment-alt")>] CommentAlt
            | [<CompiledName("far fa-comment-dots")>] CommentDots
            | [<CompiledName("far fa-comments")>] Comments
            | [<CompiledName("far fa-compass")>] Compass
            | [<CompiledName("far fa-copy")>] Copy
            | [<CompiledName("far fa-copyright")>] Copyright
            | [<CompiledName("far fa-credit-card")>] CreditCard
            | [<CompiledName("far fa-dizzy")>] Dizzy
            | [<CompiledName("far fa-dot-circle")>] DotCircle
            | [<CompiledName("far fa-edit")>] Edit
            | [<CompiledName("far fa-envelope")>] Envelope
            | [<CompiledName("far fa-envelope-open")>] EnvelopeOpen
            | [<CompiledName("far fa-eye")>] Eye
            | [<CompiledName("far fa-eye-slash")>] EyeSlash
            | [<CompiledName("far fa-file")>] File
            | [<CompiledName("far fa-file-alt")>] FileAlt
            | [<CompiledName("far fa-file-archive")>] FileArchive
            | [<CompiledName("far fa-file-audio")>] FileAudio
            | [<CompiledName("far fa-file-code")>] FileCode
            | [<CompiledName("far fa-file-excel")>] FileExcel
            | [<CompiledName("far fa-file-image")>] FileImage
            | [<CompiledName("far fa-file-pdf")>] FilePdf
            | [<CompiledName("far fa-file-powerpoint")>] FilePowerpoint
            | [<CompiledName("far fa-file-video")>] FileVideo
            | [<CompiledName("far fa-file-word")>] FileWord
            | [<CompiledName("far fa-flag")>] Flag
            | [<CompiledName("far fa-flushed")>] Flushed
            | [<CompiledName("far fa-folder")>] Folder
            | [<CompiledName("far fa-folder-open")>] FolderOpen
            | [<CompiledName("far fa-font-awesome-logo-full")>] FontAwesomeLogoFull
            | [<CompiledName("far fa-frown")>] Frown
            | [<CompiledName("far fa-frown-open")>] FrownOpen
            | [<CompiledName("far fa-futbol")>] Futbol
            | [<CompiledName("far fa-gem")>] Gem
            | [<CompiledName("far fa-grimace")>] Grimace
            | [<CompiledName("far fa-grin")>] Grin
            | [<CompiledName("far fa-grin-alt")>] GrinAlt
            | [<CompiledName("far fa-grin-beam")>] GrinBeam
            | [<CompiledName("far fa-grin-beam-sweat")>] GrinBeamSweat
            | [<CompiledName("far fa-grin-hearts")>] GrinHearts
            | [<CompiledName("far fa-grin-squint")>] GrinSquint
            | [<CompiledName("far fa-grin-squint-tears")>] GrinSquintTears
            | [<CompiledName("far fa-grin-stars")>] GrinStars
            | [<CompiledName("far fa-grin-tears")>] GrinTears
            | [<CompiledName("far fa-grin-tongue")>] GrinTongue
            | [<CompiledName("far fa-grin-tongue-squint")>] GrinTongueSquint
            | [<CompiledName("far fa-grin-tongue-wink")>] GrinTongueWink
            | [<CompiledName("far fa-grin-wink")>] GrinWink
            | [<CompiledName("far fa-hand-lizard")>] HandLizard
            | [<CompiledName("far fa-hand-paper")>] HandPaper
            | [<CompiledName("far fa-hand-peace")>] HandPeace
            | [<CompiledName("far fa-hand-point-down")>] HandPointDown
            | [<CompiledName("far fa-hand-point-left")>] HandPointLeft
            | [<CompiledName("far fa-hand-point-right")>] HandPointRight
            | [<CompiledName("far fa-hand-point-up")>] HandPointUp
            | [<CompiledName("far fa-hand-pointer")>] HandPointer
            | [<CompiledName("far fa-hand-rock")>] HandRock
            | [<CompiledName("far fa-hand-scissors")>] HandScissors
            | [<CompiledName("far fa-hand-spock")>] HandSpock
            | [<CompiledName("far fa-handshake")>] Handshake
            | [<CompiledName("far fa-hdd")>] Hdd
            | [<CompiledName("far fa-heart")>] Heart
            | [<CompiledName("far fa-hospital")>] Hospital
            | [<CompiledName("far fa-hourglass")>] Hourglass
            | [<CompiledName("far fa-id-badge")>] IdBadge
            | [<CompiledName("far fa-id-card")>] IdCard
            | [<CompiledName("far fa-image")>] Image
            | [<CompiledName("far fa-images")>] Images
            | [<CompiledName("far fa-keyboard")>] Keyboard
            | [<CompiledName("far fa-kiss")>] Kiss
            | [<CompiledName("far fa-kiss-beam")>] KissBeam
            | [<CompiledName("far fa-kiss-wink-heart")>] KissWinkHeart
            | [<CompiledName("far fa-laugh")>] Laugh
            | [<CompiledName("far fa-laugh-beam")>] LaughBeam
            | [<CompiledName("far fa-laugh-squint")>] LaughSquint
            | [<CompiledName("far fa-laugh-wink")>] LaughWink
            | [<CompiledName("far fa-lemon")>] Lemon
            | [<CompiledName("far fa-life-ring")>] LifeRing
            | [<CompiledName("far fa-lightbulb")>] Lightbulb
            | [<CompiledName("far fa-list-alt")>] ListAlt
            | [<CompiledName("far fa-map")>] Map
            | [<CompiledName("far fa-meh")>] Meh
            | [<CompiledName("far fa-meh-blank")>] MehBlank
            | [<CompiledName("far fa-meh-rolling-eyes")>] MehRollingEyes
            | [<CompiledName("far fa-minus-square")>] MinusSquare
            | [<CompiledName("far fa-money-bill-alt")>] MoneyBillAlt
            | [<CompiledName("far fa-moon")>] Moon
            | [<CompiledName("far fa-newspaper")>] Newspaper
            | [<CompiledName("far fa-object-group")>] ObjectGroup
            | [<CompiledName("far fa-object-ungroup")>] ObjectUngroup
            | [<CompiledName("far fa-paper-plane")>] PaperPlane
            | [<CompiledName("far fa-pause-circle")>] PauseCircle
            | [<CompiledName("far fa-play-circle")>] PlayCircle
            | [<CompiledName("far fa-plus-square")>] PlusSquare
            | [<CompiledName("far fa-question-circle")>] QuestionCircle
            | [<CompiledName("far fa-registered")>] Registered
            | [<CompiledName("far fa-sad-cry")>] SadCry
            | [<CompiledName("far fa-sad-tear")>] SadTear
            | [<CompiledName("far fa-save")>] Save
            | [<CompiledName("far fa-share-square")>] ShareSquare
            | [<CompiledName("far fa-smile")>] Smile
            | [<CompiledName("far fa-smile-beam")>] SmileBeam
            | [<CompiledName("far fa-smile-wink")>] SmileWink
            | [<CompiledName("far fa-snowflake")>] Snowflake
            | [<CompiledName("far fa-square")>] Square
            | [<CompiledName("far fa-star")>] Star
            | [<CompiledName("far fa-star-half")>] StarHalf
            | [<CompiledName("far fa-sticky-note")>] StickyNote
            | [<CompiledName("far fa-stop-circle")>] StopCircle
            | [<CompiledName("far fa-sun")>] Sun
            | [<CompiledName("far fa-surprise")>] Surprise
            | [<CompiledName("far fa-thumbs-down")>] ThumbsDown
            | [<CompiledName("far fa-thumbs-up")>] ThumbsUp
            | [<CompiledName("far fa-times-circle")>] TimesCircle
            | [<CompiledName("far fa-tired")>] Tired
            | [<CompiledName("far fa-trash-alt")>] TrashAlt
            | [<CompiledName("far fa-user")>] User
            | [<CompiledName("far fa-user-circle")>] UserCircle
            | [<CompiledName("far fa-window-close")>] WindowClose
            | [<CompiledName("far fa-window-maximize")>] WindowMaximize
            | [<CompiledName("far fa-window-minimize")>] WindowMinimize
            | [<CompiledName("far fa-window-restore")>] WindowRestore

        [<StringEnum>]
        type Brands =
            //| [<CompiledName("fab fa-500px")>] 500px
            | [<CompiledName("fab fa-accessible-icon")>] AccessibleIcon
            | [<CompiledName("fab fa-accusoft")>] Accusoft
            | [<CompiledName("fab fa-acquisitions-incorporated")>] AcquisitionsIncorporated
            | [<CompiledName("fab fa-adn")>] Adn
            | [<CompiledName("fab fa-adversal")>] Adversal
            | [<CompiledName("fab fa-affiliatetheme")>] Affiliatetheme
            | [<CompiledName("fab fa-algolia")>] Algolia
            | [<CompiledName("fab fa-alipay")>] Alipay
            | [<CompiledName("fab fa-amazon")>] Amazon
            | [<CompiledName("fab fa-amazon-pay")>] AmazonPay
            | [<CompiledName("fab fa-amilia")>] Amilia
            | [<CompiledName("fab fa-android")>] Android
            | [<CompiledName("fab fa-angellist")>] Angellist
            | [<CompiledName("fab fa-angrycreative")>] Angrycreative
            | [<CompiledName("fab fa-angular")>] Angular
            | [<CompiledName("fab fa-app-store")>] AppStore
            | [<CompiledName("fab fa-app-store-ios")>] AppStoreIos
            | [<CompiledName("fab fa-apper")>] Apper
            | [<CompiledName("fab fa-apple")>] Apple
            | [<CompiledName("fab fa-apple-pay")>] ApplePay
            | [<CompiledName("fab fa-asymmetrik")>] Asymmetrik
            | [<CompiledName("fab fa-audible")>] Audible
            | [<CompiledName("fab fa-autoprefixer")>] Autoprefixer
            | [<CompiledName("fab fa-avianex")>] Avianex
            | [<CompiledName("fab fa-aviato")>] Aviato
            | [<CompiledName("fab fa-aws")>] Aws
            | [<CompiledName("fab fa-bandcamp")>] Bandcamp
            | [<CompiledName("fab fa-behance")>] Behance
            | [<CompiledName("fab fa-behance-square")>] BehanceSquare
            | [<CompiledName("fab fa-bimobject")>] Bimobject
            | [<CompiledName("fab fa-bitbucket")>] Bitbucket
            | [<CompiledName("fab fa-bitcoin")>] Bitcoin
            | [<CompiledName("fab fa-bity")>] Bity
            | [<CompiledName("fab fa-black-tie")>] BlackTie
            | [<CompiledName("fab fa-blackberry")>] Blackberry
            | [<CompiledName("fab fa-blogger")>] Blogger
            | [<CompiledName("fab fa-blogger-b")>] BloggerB
            | [<CompiledName("fab fa-bluetooth")>] Bluetooth
            | [<CompiledName("fab fa-bluetooth-b")>] BluetoothB
            | [<CompiledName("fab fa-btc")>] Btc
            | [<CompiledName("fab fa-buromobelexperte")>] Buromobelexperte
            | [<CompiledName("fab fa-buysellads")>] Buysellads
            | [<CompiledName("fab fa-cc-amazon-pay")>] CcAmazonPay
            | [<CompiledName("fab fa-cc-amex")>] CcAmex
            | [<CompiledName("fab fa-cc-apple-pay")>] CcApplePay
            | [<CompiledName("fab fa-cc-diners-club")>] CcDinersClub
            | [<CompiledName("fab fa-cc-discover")>] CcDiscover
            | [<CompiledName("fab fa-cc-jcb")>] CcJcb
            | [<CompiledName("fab fa-cc-mastercard")>] CcMastercard
            | [<CompiledName("fab fa-cc-paypal")>] CcPaypal
            | [<CompiledName("fab fa-cc-stripe")>] CcStripe
            | [<CompiledName("fab fa-cc-visa")>] CcVisa
            | [<CompiledName("fab fa-centercode")>] Centercode
            | [<CompiledName("fab fa-chrome")>] Chrome
            | [<CompiledName("fab fa-cloudscale")>] Cloudscale
            | [<CompiledName("fab fa-cloudsmith")>] Cloudsmith
            | [<CompiledName("fab fa-cloudversify")>] Cloudversify
            | [<CompiledName("fab fa-codepen")>] Codepen
            | [<CompiledName("fab fa-codiepie")>] Codiepie
            | [<CompiledName("fab fa-connectdevelop")>] Connectdevelop
            | [<CompiledName("fab fa-contao")>] Contao
            | [<CompiledName("fab fa-cpanel")>] Cpanel
            | [<CompiledName("fab fa-creative-commons")>] CreativeCommons
            | [<CompiledName("fab fa-creative-commons-by")>] CreativeCommonsBy
            | [<CompiledName("fab fa-creative-commons-nc")>] CreativeCommonsNc
            | [<CompiledName("fab fa-creative-commons-nc-eu")>] CreativeCommonsNcEu
            | [<CompiledName("fab fa-creative-commons-nc-jp")>] CreativeCommonsNcJp
            | [<CompiledName("fab fa-creative-commons-nd")>] CreativeCommonsNd
            | [<CompiledName("fab fa-creative-commons-pd")>] CreativeCommonsPd
            | [<CompiledName("fab fa-creative-commons-pd-alt")>] CreativeCommonsPdAlt
            | [<CompiledName("fab fa-creative-commons-remix")>] CreativeCommonsRemix
            | [<CompiledName("fab fa-creative-commons-sa")>] CreativeCommonsSa
            | [<CompiledName("fab fa-creative-commons-sampling")>] CreativeCommonsSampling
            | [<CompiledName("fab fa-creative-commons-sampling-plus")>] CreativeCommonsSamplingPlus
            | [<CompiledName("fab fa-creative-commons-share")>] CreativeCommonsShare
            | [<CompiledName("fab fa-creative-commons-zero")>] CreativeCommonsZero
            | [<CompiledName("fab fa-critical-role")>] CriticalRole
            | [<CompiledName("fab fa-css3")>] Css3
            | [<CompiledName("fab fa-css3-alt")>] Css3Alt
            | [<CompiledName("fab fa-cuttlefish")>] Cuttlefish
            | [<CompiledName("fab fa-d-and-d")>] DAndD
            | [<CompiledName("fab fa-d-and-d-beyond")>] DAndDBeyond
            | [<CompiledName("fab fa-dashcube")>] Dashcube
            | [<CompiledName("fab fa-delicious")>] Delicious
            | [<CompiledName("fab fa-deploydog")>] Deploydog
            | [<CompiledName("fab fa-deskpro")>] Deskpro
            | [<CompiledName("fab fa-dev")>] Dev
            | [<CompiledName("fab fa-deviantart")>] Deviantart
            | [<CompiledName("fab fa-digg")>] Digg
            | [<CompiledName("fab fa-digital-ocean")>] DigitalOcean
            | [<CompiledName("fab fa-discord")>] Discord
            | [<CompiledName("fab fa-discourse")>] Discourse
            | [<CompiledName("fab fa-dochub")>] Dochub
            | [<CompiledName("fab fa-docker")>] Docker
            | [<CompiledName("fab fa-draft2digital")>] Draft2digital
            | [<CompiledName("fab fa-dribbble")>] Dribbble
            | [<CompiledName("fab fa-dribbble-square")>] DribbbleSquare
            | [<CompiledName("fab fa-dropbox")>] Dropbox
            | [<CompiledName("fab fa-drupal")>] Drupal
            | [<CompiledName("fab fa-dyalog")>] Dyalog
            | [<CompiledName("fab fa-earlybirds")>] Earlybirds
            | [<CompiledName("fab fa-ebay")>] Ebay
            | [<CompiledName("fab fa-edge")>] Edge
            | [<CompiledName("fab fa-elementor")>] Elementor
            | [<CompiledName("fab fa-ello")>] Ello
            | [<CompiledName("fab fa-ember")>] Ember
            | [<CompiledName("fab fa-empire")>] Empire
            | [<CompiledName("fab fa-envira")>] Envira
            | [<CompiledName("fab fa-erlang")>] Erlang
            | [<CompiledName("fab fa-ethereum")>] Ethereum
            | [<CompiledName("fab fa-etsy")>] Etsy
            | [<CompiledName("fab fa-expeditedssl")>] Expeditedssl
            | [<CompiledName("fab fa-facebook")>] Facebook
            | [<CompiledName("fab fa-facebook-f")>] FacebookF
            | [<CompiledName("fab fa-facebook-messenger")>] FacebookMessenger
            | [<CompiledName("fab fa-facebook-square")>] FacebookSquare
            | [<CompiledName("fab fa-fantasy-flight-games")>] FantasyFlightGames
            | [<CompiledName("fab fa-firefox")>] Firefox
            | [<CompiledName("fab fa-first-order")>] FirstOrder
            | [<CompiledName("fab fa-first-order-alt")>] FirstOrderAlt
            | [<CompiledName("fab fa-firstdraft")>] Firstdraft
            | [<CompiledName("fab fa-flickr")>] Flickr
            | [<CompiledName("fab fa-flipboard")>] Flipboard
            | [<CompiledName("fab fa-fly")>] Fly
            | [<CompiledName("fab fa-font-awesome")>] FontAwesome
            | [<CompiledName("fab fa-font-awesome-alt")>] FontAwesomeAlt
            | [<CompiledName("fab fa-font-awesome-flag")>] FontAwesomeFlag
            | [<CompiledName("fab fa-font-awesome-logo-full")>] FontAwesomeLogoFull
            | [<CompiledName("fab fa-fonticons")>] Fonticons
            | [<CompiledName("fab fa-fonticons-fi")>] FonticonsFi
            | [<CompiledName("fab fa-fort-awesome")>] FortAwesome
            | [<CompiledName("fab fa-fort-awesome-alt")>] FortAwesomeAlt
            | [<CompiledName("fab fa-forumbee")>] Forumbee
            | [<CompiledName("fab fa-foursquare")>] Foursquare
            | [<CompiledName("fab fa-free-code-camp")>] FreeCodeCamp
            | [<CompiledName("fab fa-freebsd")>] Freebsd
            | [<CompiledName("fab fa-fulcrum")>] Fulcrum
            | [<CompiledName("fab fa-galactic-republic")>] GalacticRepublic
            | [<CompiledName("fab fa-galactic-senate")>] GalacticSenate
            | [<CompiledName("fab fa-get-pocket")>] GetPocket
            | [<CompiledName("fab fa-gg")>] Gg
            | [<CompiledName("fab fa-gg-circle")>] GgCircle
            | [<CompiledName("fab fa-git")>] Git
            | [<CompiledName("fab fa-git-square")>] GitSquare
            | [<CompiledName("fab fa-github")>] Github
            | [<CompiledName("fab fa-github-alt")>] GithubAlt
            | [<CompiledName("fab fa-github-square")>] GithubSquare
            | [<CompiledName("fab fa-gitkraken")>] Gitkraken
            | [<CompiledName("fab fa-gitlab")>] Gitlab
            | [<CompiledName("fab fa-gitter")>] Gitter
            | [<CompiledName("fab fa-glide")>] Glide
            | [<CompiledName("fab fa-glide-g")>] GlideG
            | [<CompiledName("fab fa-gofore")>] Gofore
            | [<CompiledName("fab fa-goodreads")>] Goodreads
            | [<CompiledName("fab fa-goodreads-g")>] GoodreadsG
            | [<CompiledName("fab fa-google")>] Google
            | [<CompiledName("fab fa-google-drive")>] GoogleDrive
            | [<CompiledName("fab fa-google-play")>] GooglePlay
            | [<CompiledName("fab fa-google-plus")>] GooglePlus
            | [<CompiledName("fab fa-google-plus-g")>] GooglePlusG
            | [<CompiledName("fab fa-google-plus-square")>] GooglePlusSquare
            | [<CompiledName("fab fa-google-wallet")>] GoogleWallet
            | [<CompiledName("fab fa-gratipay")>] Gratipay
            | [<CompiledName("fab fa-grav")>] Grav
            | [<CompiledName("fab fa-gripfire")>] Gripfire
            | [<CompiledName("fab fa-grunt")>] Grunt
            | [<CompiledName("fab fa-gulp")>] Gulp
            | [<CompiledName("fab fa-hacker-news")>] HackerNews
            | [<CompiledName("fab fa-hacker-news-square")>] HackerNewsSquare
            | [<CompiledName("fab fa-hackerrank")>] Hackerrank
            | [<CompiledName("fab fa-hips")>] Hips
            | [<CompiledName("fab fa-hire-a-helper")>] HireAHelper
            | [<CompiledName("fab fa-hooli")>] Hooli
            | [<CompiledName("fab fa-hornbill")>] Hornbill
            | [<CompiledName("fab fa-hotjar")>] Hotjar
            | [<CompiledName("fab fa-houzz")>] Houzz
            | [<CompiledName("fab fa-html5")>] Html5
            | [<CompiledName("fab fa-hubspot")>] Hubspot
            | [<CompiledName("fab fa-imdb")>] Imdb
            | [<CompiledName("fab fa-instagram")>] Instagram
            | [<CompiledName("fab fa-internet-explorer")>] InternetExplorer
            | [<CompiledName("fab fa-ioxhost")>] Ioxhost
            | [<CompiledName("fab fa-itunes")>] Itunes
            | [<CompiledName("fab fa-itunes-note")>] ItunesNote
            | [<CompiledName("fab fa-java")>] Java
            | [<CompiledName("fab fa-jedi-order")>] JediOrder
            | [<CompiledName("fab fa-jenkins")>] Jenkins
            | [<CompiledName("fab fa-joget")>] Joget
            | [<CompiledName("fab fa-joomla")>] Joomla
            | [<CompiledName("fab fa-js")>] Js
            | [<CompiledName("fab fa-js-square")>] JsSquare
            | [<CompiledName("fab fa-jsfiddle")>] Jsfiddle
            | [<CompiledName("fab fa-kaggle")>] Kaggle
            | [<CompiledName("fab fa-keybase")>] Keybase
            | [<CompiledName("fab fa-keycdn")>] Keycdn
            | [<CompiledName("fab fa-kickstarter")>] Kickstarter
            | [<CompiledName("fab fa-kickstarter-k")>] KickstarterK
            | [<CompiledName("fab fa-korvue")>] Korvue
            | [<CompiledName("fab fa-laravel")>] Laravel
            | [<CompiledName("fab fa-lastfm")>] Lastfm
            | [<CompiledName("fab fa-lastfm-square")>] LastfmSquare
            | [<CompiledName("fab fa-leanpub")>] Leanpub
            | [<CompiledName("fab fa-less")>] Less
            | [<CompiledName("fab fa-line")>] Line
            | [<CompiledName("fab fa-linkedin")>] Linkedin
            | [<CompiledName("fab fa-linkedin-in")>] LinkedinIn
            | [<CompiledName("fab fa-linode")>] Linode
            | [<CompiledName("fab fa-linux")>] Linux
            | [<CompiledName("fab fa-lyft")>] Lyft
            | [<CompiledName("fab fa-magento")>] Magento
            | [<CompiledName("fab fa-mailchimp")>] Mailchimp
            | [<CompiledName("fab fa-mandalorian")>] Mandalorian
            | [<CompiledName("fab fa-markdown")>] Markdown
            | [<CompiledName("fab fa-mastodon")>] Mastodon
            | [<CompiledName("fab fa-maxcdn")>] Maxcdn
            | [<CompiledName("fab fa-medapps")>] Medapps
            | [<CompiledName("fab fa-medium")>] Medium
            | [<CompiledName("fab fa-medium-m")>] MediumM
            | [<CompiledName("fab fa-medrt")>] Medrt
            | [<CompiledName("fab fa-meetup")>] Meetup
            | [<CompiledName("fab fa-megaport")>] Megaport
            | [<CompiledName("fab fa-microsoft")>] Microsoft
            | [<CompiledName("fab fa-mix")>] Mix
            | [<CompiledName("fab fa-mixcloud")>] Mixcloud
            | [<CompiledName("fab fa-mizuni")>] Mizuni
            | [<CompiledName("fab fa-modx")>] Modx
            | [<CompiledName("fab fa-monero")>] Monero
            | [<CompiledName("fab fa-napster")>] Napster
            | [<CompiledName("fab fa-neos")>] Neos
            | [<CompiledName("fab fa-nimblr")>] Nimblr
            | [<CompiledName("fab fa-nintendo-switch")>] NintendoSwitch
            | [<CompiledName("fab fa-node")>] Node
            | [<CompiledName("fab fa-node-js")>] NodeJs
            | [<CompiledName("fab fa-npm")>] Npm
            | [<CompiledName("fab fa-ns8")>] Ns8
            | [<CompiledName("fab fa-nutritionix")>] Nutritionix
            | [<CompiledName("fab fa-odnoklassniki")>] Odnoklassniki
            | [<CompiledName("fab fa-odnoklassniki-square")>] OdnoklassnikiSquare
            | [<CompiledName("fab fa-old-republic")>] OldRepublic
            | [<CompiledName("fab fa-opencart")>] Opencart
            | [<CompiledName("fab fa-openid")>] Openid
            | [<CompiledName("fab fa-opera")>] Opera
            | [<CompiledName("fab fa-optin-monster")>] OptinMonster
            | [<CompiledName("fab fa-osi")>] Osi
            | [<CompiledName("fab fa-page4")>] Page4
            | [<CompiledName("fab fa-pagelines")>] Pagelines
            | [<CompiledName("fab fa-palfed")>] Palfed
            | [<CompiledName("fab fa-patreon")>] Patreon
            | [<CompiledName("fab fa-paypal")>] Paypal
            | [<CompiledName("fab fa-penny-arcade")>] PennyArcade
            | [<CompiledName("fab fa-periscope")>] Periscope
            | [<CompiledName("fab fa-phabricator")>] Phabricator
            | [<CompiledName("fab fa-phoenix-framework")>] PhoenixFramework
            | [<CompiledName("fab fa-phoenix-squadron")>] PhoenixSquadron
            | [<CompiledName("fab fa-php")>] Php
            | [<CompiledName("fab fa-pied-piper")>] PiedPiper
            | [<CompiledName("fab fa-pied-piper-alt")>] PiedPiperAlt
            | [<CompiledName("fab fa-pied-piper-hat")>] PiedPiperHat
            | [<CompiledName("fab fa-pied-piper-pp")>] PiedPiperPp
            | [<CompiledName("fab fa-pinterest")>] Pinterest
            | [<CompiledName("fab fa-pinterest-p")>] PinterestP
            | [<CompiledName("fab fa-pinterest-square")>] PinterestSquare
            | [<CompiledName("fab fa-playstation")>] Playstation
            | [<CompiledName("fab fa-product-hunt")>] ProductHunt
            | [<CompiledName("fab fa-pushed")>] Pushed
            | [<CompiledName("fab fa-python")>] Python
            | [<CompiledName("fab fa-qq")>] Qq
            | [<CompiledName("fab fa-quinscape")>] Quinscape
            | [<CompiledName("fab fa-quora")>] Quora
            | [<CompiledName("fab fa-r-project")>] RProject
            | [<CompiledName("fab fa-ravelry")>] Ravelry
            | [<CompiledName("fab fa-react")>] React
            | [<CompiledName("fab fa-readme")>] Readme
            | [<CompiledName("fab fa-rebel")>] Rebel
            | [<CompiledName("fab fa-red-river")>] RedRiver
            | [<CompiledName("fab fa-reddit")>] Reddit
            | [<CompiledName("fab fa-reddit-alien")>] RedditAlien
            | [<CompiledName("fab fa-reddit-square")>] RedditSquare
            | [<CompiledName("fab fa-renren")>] Renren
            | [<CompiledName("fab fa-replyd")>] Replyd
            | [<CompiledName("fab fa-researchgate")>] Researchgate
            | [<CompiledName("fab fa-resolving")>] Resolving
            | [<CompiledName("fab fa-rev")>] Rev
            | [<CompiledName("fab fa-rocketchat")>] Rocketchat
            | [<CompiledName("fab fa-rockrms")>] Rockrms
            | [<CompiledName("fab fa-safari")>] Safari
            | [<CompiledName("fab fa-sass")>] Sass
            | [<CompiledName("fab fa-schlix")>] Schlix
            | [<CompiledName("fab fa-scribd")>] Scribd
            | [<CompiledName("fab fa-searchengin")>] Searchengin
            | [<CompiledName("fab fa-sellcast")>] Sellcast
            | [<CompiledName("fab fa-sellsy")>] Sellsy
            | [<CompiledName("fab fa-servicestack")>] Servicestack
            | [<CompiledName("fab fa-shirtsinbulk")>] Shirtsinbulk
            | [<CompiledName("fab fa-shopware")>] Shopware
            | [<CompiledName("fab fa-simplybuilt")>] Simplybuilt
            | [<CompiledName("fab fa-sistrix")>] Sistrix
            | [<CompiledName("fab fa-sith")>] Sith
            | [<CompiledName("fab fa-skyatlas")>] Skyatlas
            | [<CompiledName("fab fa-skype")>] Skype
            | [<CompiledName("fab fa-slack")>] Slack
            | [<CompiledName("fab fa-slack-hash")>] SlackHash
            | [<CompiledName("fab fa-slideshare")>] Slideshare
            | [<CompiledName("fab fa-snapchat")>] Snapchat
            | [<CompiledName("fab fa-snapchat-ghost")>] SnapchatGhost
            | [<CompiledName("fab fa-snapchat-square")>] SnapchatSquare
            | [<CompiledName("fab fa-soundcloud")>] Soundcloud
            | [<CompiledName("fab fa-speakap")>] Speakap
            | [<CompiledName("fab fa-spotify")>] Spotify
            | [<CompiledName("fab fa-squarespace")>] Squarespace
            | [<CompiledName("fab fa-stack-exchange")>] StackExchange
            | [<CompiledName("fab fa-stack-overflow")>] StackOverflow
            | [<CompiledName("fab fa-staylinked")>] Staylinked
            | [<CompiledName("fab fa-steam")>] Steam
            | [<CompiledName("fab fa-steam-square")>] SteamSquare
            | [<CompiledName("fab fa-steam-symbol")>] SteamSymbol
            | [<CompiledName("fab fa-sticker-mule")>] StickerMule
            | [<CompiledName("fab fa-strava")>] Strava
            | [<CompiledName("fab fa-stripe")>] Stripe
            | [<CompiledName("fab fa-stripe-s")>] StripeS
            | [<CompiledName("fab fa-studiovinari")>] Studiovinari
            | [<CompiledName("fab fa-stumbleupon")>] Stumbleupon
            | [<CompiledName("fab fa-stumbleupon-circle")>] StumbleuponCircle
            | [<CompiledName("fab fa-superpowers")>] Superpowers
            | [<CompiledName("fab fa-supple")>] Supple
            | [<CompiledName("fab fa-teamspeak")>] Teamspeak
            | [<CompiledName("fab fa-telegram")>] Telegram
            | [<CompiledName("fab fa-telegram-plane")>] TelegramPlane
            | [<CompiledName("fab fa-tencent-weibo")>] TencentWeibo
            | [<CompiledName("fab fa-the-red-yeti")>] TheRedYeti
            | [<CompiledName("fab fa-themeco")>] Themeco
            | [<CompiledName("fab fa-themeisle")>] Themeisle
            | [<CompiledName("fab fa-think-peaks")>] ThinkPeaks
            | [<CompiledName("fab fa-trade-federation")>] TradeFederation
            | [<CompiledName("fab fa-trello")>] Trello
            | [<CompiledName("fab fa-tripadvisor")>] Tripadvisor
            | [<CompiledName("fab fa-tumblr")>] Tumblr
            | [<CompiledName("fab fa-tumblr-square")>] TumblrSquare
            | [<CompiledName("fab fa-twitch")>] Twitch
            | [<CompiledName("fab fa-twitter")>] Twitter
            | [<CompiledName("fab fa-twitter-square")>] TwitterSquare
            | [<CompiledName("fab fa-typo3")>] Typo3
            | [<CompiledName("fab fa-uber")>] Uber
            | [<CompiledName("fab fa-uikit")>] Uikit
            | [<CompiledName("fab fa-uniregistry")>] Uniregistry
            | [<CompiledName("fab fa-untappd")>] Untappd
            | [<CompiledName("fab fa-usb")>] Usb
            | [<CompiledName("fab fa-ussunnah")>] Ussunnah
            | [<CompiledName("fab fa-vaadin")>] Vaadin
            | [<CompiledName("fab fa-viacoin")>] Viacoin
            | [<CompiledName("fab fa-viadeo")>] Viadeo
            | [<CompiledName("fab fa-viadeo-square")>] ViadeoSquare
            | [<CompiledName("fab fa-viber")>] Viber
            | [<CompiledName("fab fa-vimeo")>] Vimeo
            | [<CompiledName("fab fa-vimeo-square")>] VimeoSquare
            | [<CompiledName("fab fa-vimeo-v")>] VimeoV
            | [<CompiledName("fab fa-vine")>] Vine
            | [<CompiledName("fab fa-vk")>] Vk
            | [<CompiledName("fab fa-vnv")>] Vnv
            | [<CompiledName("fab fa-vuejs")>] Vuejs
            | [<CompiledName("fab fa-weebly")>] Weebly
            | [<CompiledName("fab fa-weibo")>] Weibo
            | [<CompiledName("fab fa-weixin")>] Weixin
            | [<CompiledName("fab fa-whatsapp")>] Whatsapp
            | [<CompiledName("fab fa-whatsapp-square")>] WhatsappSquare
            | [<CompiledName("fab fa-whmcs")>] Whmcs
            | [<CompiledName("fab fa-wikipedia-w")>] WikipediaW
            | [<CompiledName("fab fa-windows")>] Windows
            | [<CompiledName("fab fa-wix")>] Wix
            | [<CompiledName("fab fa-wizards-of-the-coast")>] WizardsOfTheCoast
            | [<CompiledName("fab fa-wolf-pack-battalion")>] WolfPackBattalion
            | [<CompiledName("fab fa-wordpress")>] Wordpress
            | [<CompiledName("fab fa-wordpress-simple")>] WordpressSimple
            | [<CompiledName("fab fa-wpbeginner")>] Wpbeginner
            | [<CompiledName("fab fa-wpexplorer")>] Wpexplorer
            | [<CompiledName("fab fa-wpforms")>] Wpforms
            | [<CompiledName("fab fa-wpressr")>] Wpressr
            | [<CompiledName("fab fa-xbox")>] Xbox
            | [<CompiledName("fab fa-xing")>] Xing
            | [<CompiledName("fab fa-xing-square")>] XingSquare
            | [<CompiledName("fab fa-y-combinator")>] YCombinator
            | [<CompiledName("fab fa-yahoo")>] Yahoo
            | [<CompiledName("fab fa-yandex")>] Yandex
            | [<CompiledName("fab fa-yandex-international")>] YandexInternational
            | [<CompiledName("fab fa-yelp")>] Yelp
            | [<CompiledName("fab fa-yoast")>] Yoast
            | [<CompiledName("fab fa-youtube")>] Youtube
            | [<CompiledName("fab fa-youtube-square")>] YoutubeSquare
            | [<CompiledName("fab fa-zhihu")>] Zhihu